### ISSUE TITLE
Az Module not installed in Azure Powershell Action?

### ISSUE THREAD

**Issue by jennirethi** [Azure/powershell#28]
![image](https://user-images.githubusercontent.com/74195196/109231054-7f031500-778b-11eb-93ad-08de89fb5210.png)

**Comment by AmrutaKawade** [comment]
@jennirethi can you share yml of task?

**Comment by jennirethi** [comment]
- name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzVM -ResourceGroupName "ResourceGroup11"
        azPSVersion: '3.1.0'

**Comment by AmrutaKawade** [comment]
@jennirethi are you using github runner or self hosted runner?
if github runner which os?

**Comment by jennirethi** [comment]
ubuntu-latest

**Comment by AmrutaKawade** [comment]
ubuntu-latest might be pointing to ubuntu 20.04 which doesn't have az 3.1.0 version available.
You can verify ubuntu version in logs

![image](https://user-images.githubusercontent.com/65217380/109756274-a33c7700-7c0d-11eb-9f83-6b98a79c3ad2.png)

Az 3.1.0 is available in `ubuntu-18.04` 

Instead of `ubuntu-latest` use `ubuntu-18.04`

**Comment by AmrutaKawade** [comment]
@jennirethi let me know if this resolves your problem

**Comment by jennirethi** [comment]
Interesting - it is using version: '2.277.1'

**Comment by jennirethi** [comment]
Ubuntu - 20.04.2

**Comment by jennirethi** [comment]
Changing to 18.04 resolved the issue.
