### ISSUE TITLE
Make PS faster by removing the calls to get progress info

### ISSUE THREAD

**Issue by kaverma** [Azure/powershell#48]
There is a feature request for Powershell -

> The progress bar in PowerShell makes Invoke-WebRequest literally 50x slower.  Downloading the .iso for building dev images would probably hit the default 60 minute timeout with progress enabled.  With progress disabled it completes in a few minutes like you’d expect.  This is especially galling because progress is not rendered by pipelines so it is wasted work.
>  
> Can we start a discussion with the ADO and GitHub Actions folks to see if their PowerShell tasks can disable progress automatically?  That would be an immediate boost in pipeline performance with no downside that I’m aware of.  Disabling progress in PowerShell just requires a single line of setup:
>               $ProgressPreference = 'SilentlyContinue';

 
For the above can we please check if any changes are needed in the powershell Action? 
Related on ADO - https://dev.azure.com/mseng/AzureDevOps/_workitems/edit/1914047 
Related - https://github.com/Azure/pipelines/issues/53

**Comment by BALAGA-GAYATRI** [comment]
We are not using `Invoke-WebRequest` in our action so we wouldn't require this.

**Comment by dmachaj** [comment]
@BALAGA-GAYATRI this action can run arbitrary PowerShell.  I filed this because __my__ call to `Invoke-WebRequest` was incredibly slow.

**Comment by BALAGA-GAYATRI** [comment]
I understand @dmachaj. I'm just wondering if having this line- `$ProgressPreference = 'SilentlyContinue'` in your input inline script before calling ` Invoke-WebRequest` in your action workflow can help here.

**Comment by dmachaj** [comment]
Yes, that would fix it for my inline script (and __only__ my inline script).  Now that I know this problem exists I can work around it.  The purpose of this GH issue is that it should be possible to bake this into the pipeline implementation so that people don't need to know that.  It just magically gets faster for everyone who calls something that renders progress.  I found this performance bottleneck surprising and unexpected so I think that many people are affected unknowingly.

Also, there should be no real downside to making this change because progress can't be rendered in the pipeline anyway.  That is wasted work.
